"""Pydantic data models for ai-ir."""

from __future__ import annotations

from datetime import datetime
from typing import Literal, Optional

from pydantic import BaseModel, field_validator


# ---------------------------------------------------------------------------
# Input models
# ---------------------------------------------------------------------------


class SlackMessage(BaseModel):
    """A single message from a scat/stail JSON export."""

    user_id: str
    user_name: str
    post_type: Literal["user", "bot"]
    timestamp: datetime
    timestamp_unix: str
    text: str
    files: list = []
    thread_timestamp_unix: str = ""
    is_reply: bool = False


class SlackExport(BaseModel):
    """Top-level scat/stail JSON export document."""

    export_timestamp: datetime
    channel_name: str
    messages: list[SlackMessage]


# ---------------------------------------------------------------------------
# Preprocessed models
# ---------------------------------------------------------------------------


class IoC(BaseModel):
    """An extracted and defanged Indicator of Compromise."""

    original: str
    defanged: str
    type: str  # "ip", "url", "domain", "email", "hash"


class ProcessedMessage(BaseModel):
    """A Slack message after IoC defanging and injection sanitization."""

    user_id: str
    user_name: str
    post_type: str
    timestamp: datetime
    timestamp_unix: str
    text: str  # defanged and sanitized text, wrapped in nonce-tagged block
    files: list = []
    thread_timestamp_unix: str = ""
    is_reply: bool = False
    iocs: list[IoC] = []
    has_injection_risk: bool = False
    injection_warnings: list[str] = []


class ProcessedExport(BaseModel):
    """A processed export document with security metadata."""

    export_timestamp: datetime
    channel_name: str
    messages: list[ProcessedMessage]
    security_warnings: list[str] = []
    sanitization_nonce: str = ""
    """Random nonce embedded in <user_message_{nonce}> wrapping tags.

    All messages in this export share the same nonce. LLM system prompts
    must reference this nonce so the model knows which tags delimit user data.
    An empty string indicates the export was produced before nonce support was added;
    callers should generate a fallback nonce in that case.
    """


# ---------------------------------------------------------------------------
# Analysis models
# ---------------------------------------------------------------------------


class TimelineEvent(BaseModel):
    """A single event in the incident timeline."""

    timestamp: str
    actor: str
    event: str


class IncidentSummary(BaseModel):
    """Structured incident summary generated by LLM."""

    title: str
    severity: Optional[str] = None
    affected_systems: list[str] = []
    timeline: list[TimelineEvent] = []
    root_cause: str = ""
    resolution: str = ""
    summary: str = ""


class Action(BaseModel):
    """A single action taken by a participant during the incident."""

    timestamp: str
    purpose: str
    method: str
    findings: str = ""

    @field_validator("purpose", "method", "findings", mode="before")
    @classmethod
    def coerce_list_to_str(cls, v: object) -> str:
        """Normalize LLM output: join lists, convert None to empty string."""
        if v is None:
            return ""
        if isinstance(v, list):
            return "\n".join(str(item) for item in v)
        return v


class ParticipantActivity(BaseModel):
    """Activity summary for a single participant."""

    user_name: str
    role_hint: str
    actions: list[Action] = []


class ActivityAnalysis(BaseModel):
    """Per-participant activity analysis."""

    incident_id: str
    channel: str
    participants: list[ParticipantActivity] = []


class Relationship(BaseModel):
    """A relationship between two participants."""

    from_user: str
    to_user: Optional[str] = None
    relationship_type: str
    description: str


class ParticipantRole(BaseModel):
    """Inferred role for a single participant."""

    user_name: str
    inferred_role: str
    confidence: str  # "high", "medium", "low"
    evidence: list[str] = []


class RoleAnalysis(BaseModel):
    """Role and relationship inference results."""

    incident_id: str
    channel: str
    participants: list[ParticipantRole] = []
    relationships: list[Relationship] = []


# ---------------------------------------------------------------------------
# Knowledge models
# ---------------------------------------------------------------------------


class TacticSource(BaseModel):
    """Source metadata for a tactic knowledge document."""

    channel: str
    participants: list[str] = []


class Tactic(BaseModel):
    """A reusable investigation tactic extracted from an IR conversation."""

    id: str
    title: str
    purpose: str
    category: str  # e.g., "log-analysis", "network-analysis"
    tools: list[str] = []
    procedure: str
    observations: str
    tags: list[str] = []
    source: TacticSource
    created_at: str  # ISO date string (YYYY-MM-DD)

    @field_validator("procedure", "observations", mode="before")
    @classmethod
    def coerce_list_to_str(cls, v: object) -> str:
        """Join list values returned by some LLMs into a newline-separated string."""
        if isinstance(v, list):
            return "\n".join(str(item) for item in v)
        return v
